#include <raylib.h>

#include "colors.hpp"

#define REGISTER_COLOR(color) \
	state[#color] = state.create_table_with("r", color.r, "g", color.g, "b", color.b, "a", color.a)

void register_colors(sol::state_view state) {
	REGISTER_COLOR(LIGHTGRAY);
	REGISTER_COLOR(GRAY);
	REGISTER_COLOR(DARKGRAY);
	REGISTER_COLOR(YELLOW);
	REGISTER_COLOR(GOLD);
	REGISTER_COLOR(ORANGE);
	REGISTER_COLOR(PINK);
	REGISTER_COLOR(RED);
	REGISTER_COLOR(MAROON);
	REGISTER_COLOR(GREEN);
	REGISTER_COLOR(LIME);
	REGISTER_COLOR(DARKGREEN);
	REGISTER_COLOR(SKYBLUE);
	REGISTER_COLOR(BLUE);
	REGISTER_COLOR(DARKBLUE);
	REGISTER_COLOR(PURPLE);
	REGISTER_COLOR(VIOLET);
	REGISTER_COLOR(DARKPURPLE);
	REGISTER_COLOR(BEIGE);
	REGISTER_COLOR(BROWN);
	REGISTER_COLOR(DARKBROWN);

	REGISTER_COLOR(WHITE);
	REGISTER_COLOR(BLACK);
	REGISTER_COLOR(BLANK);
	REGISTER_COLOR(MAGENTA);
	REGISTER_COLOR(RAYWHITE);
}
