[PlayerShip.Texture]
path = "textures/playerShip1_blue.png"

[PlayerShip.Position]
x = 400
y = 500

[PlayerShip.LinearSpeed]
value = 300

[PlayerShip.MoveOnArrows]

# Bullet spawner
[PlayerShip.SceneSql]
path = "bullet.toml"

[PlayerShip.SpawnOnKey]
cooldown = 0.2
